- name: Setup Local DNS with dnsmasq on Ubuntu
  hosts: master
  become: true
  tasks:

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    - name: Backup default dnsmasq config
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.bak
        remote_src: yes
        mode: '0644'

    - name: Configure dnsmasq for local domain
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart dnsmasq

    - name: Enable and start dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

  handlers:
    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
