---
- name: Ensure DNS settings persist across reboots and add nameserver
  hosts: all
  become: true
  tasks:

    - name: Ensure DNS settings in systemd-resolved.conf are correct
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNS='
        line: 'DNS=10.10.100.105 8.8.8.8'
        insertafter: EOF
        create: yes
      notify:
        - Restart systemd-resolved

    - name: Ensure /etc/resolv.conf points to systemd stub resolver
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link   # Ensure the symlink points to the systemd stub resolver

    - name: Ensure systemd-resolved is enabled and started
      systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Append 10.10.100.105 as a nameserver to /etc/resolv.conf if not present
      blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver 10.10.100.105
        insertafter: EOF
        create: yes
        state: present

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
