---
- name: Ensure DNS settings persist across reboots and add nameserver
  hosts: all
  become: true
  tasks:

    - name: Ensure DNS settings in systemd-resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNS='
        line: 'DNS=10.10.100.105 8.8.8.8'
        insertafter: EOF
        create: yes
      notify:
        - Restart systemd-resolved

    - name: Add 10.10.100.105 as nameserver to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.10.100.105'
        state: present
        insertafter: EOF
        create: yes

    - name: Ensure systemd-resolved is enabled and started
      systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Ensure /etc/resolv.conf is correctly symlinked to systemd stub resolver
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link   # Ensure the symlink points to the systemd stub resolver

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
