---
- name: Enable br_netfilter kernel module
  hosts: all  # Applies to all nodes (master and workers)
  become: true  # Run tasks with elevated privileges
  tasks:
    - name: Ensure br_netfilter kernel module is loaded
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure br_netfilter is loaded on boot
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "br_netfilter"
        create: yes
        state: present

    - name: Ensure sysctl settings for Kubernetes networking
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
        - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
      when: ansible_os_family == "Debian"  # Applies to Debian/Ubuntu systems

    - name: Ensure sysctl settings are persisted
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        owner: root
        group: root
        mode: '0644'