- name: Disable swap on servers and configure sysctl params for kubernetes setup
  hosts: all
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Ensure swap is commented in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^.*\bswap\b.*$'
        replace: '#\0'

    - name: Create sysctl configuration file
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl parameters
      command: sysctl --system