---
- name: Install NFS client utilities
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Optional: This keeps the cache valid for 1 hour

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present