- name: Join Kubernetes cluster
  hosts: workers
  become: true
  tasks:
    - name: Fetch kubeadm join command from master
      shell: cat /tmp/kubeadm_join_command.txt
      delegate_to: master
      register: join_command_output

    - name: Write the kubeadm join command to a local file on workers
      copy:
        content: "{{ join_command_output.stdout }}"
        dest: /tmp/kubeadm_join_command.txt
        mode: '0755'

    - name: Verify the kubeadm join command file exists on workers
      stat:
        path: /tmp/kubeadm_join_command.txt
      register: join_file_status

    - name: Fail if join command file is missing on workers
      fail:
        msg: "The kubeadm join command file was not copied to the worker node."
      when: not join_file_status.stat.exists

    - name: Execute the kubeadm join command
      command: bash /tmp/kubeadm_join_command.txt