- name: Install kubeadm, kubelet and kubectl
  hosts: all
  become: true
  tasks:
    - name: Install Docker and Kubernetes packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubelet, kubeadm, and kubectl packages
      command: apt-mark hold kubelet kubeadm kubectl
